spring:
  jpa:
    open-in-view: false

---
spring:
  config.activate.on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate: info

---
spring:
  config.activate.on-profile: test

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: off
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema-h2.sql
