[[User-API]]
= *User API*

[[유저-생성-API]]
== *1. 유저 생성 API*

=== *1-1 성공*

operation::user-controller-test/create-user-success[snippets='http-request,request-fields,http-response']

=== *1-2 실패 - 유효하지 않은 유저 이름*

operation::user-controller-test/create-user-fail-user-name-blank[snippets='http-request,http-response']

=== *1-3 실패 - 음수의 초기 금액*

operation::user-controller-test/create-user-fail-money-negative[snippets='http-request,http-response']

=== *1-2 실패 - 유효하지 않은 유저 이름*

operation::user-controller-test/create-user-fail-user-name-blank[snippets='http-request,http-response']

[[유저-조회-API]]
== *2. 유저 조회 API*

=== *2-1 성공*

operation::user-controller-test/get-user-information-success[snippets='http-request,path-parameters,http-response,response-fields']

=== *2-2 실패 - 음수 유저 id*

operation::user-controller-test/get-user-information-fail-user-id-negative[snippets='http-request,path-parameters,http-response']

=== *2-3 실패 - 존재하지 않는 유저 id*

operation::user-controller-test/get-user-information-fail-user-id-not-exist[snippets='http-request,path-parameters,http-response']

[[유저-돈-충전-API]]
== *3. 유저 돈 충전 API*

=== *3-1 성공*

operation::user-controller-test/add-user-money-success[snippets='http-request,request-fields,http-response']

=== *3-2 실패 - 음수 유저 id*

operation::user-controller-test/add-user-money-fail-user-id-negative[snippets='http-request,http-response']

=== *3-3 실패 - 존재하지 않는 유저 id*

operation::user-controller-test/add-user-money-fail-user-id-not-exist[snippets='http-request,http-response']

=== *3-4 실패 - 음수의 충전 금액*

operation::user-controller-test/add-user-money-fail-charge-negative[snippets='http-request,http-response']

[[유저-돈-출금-API]]
== *4. 유저 돈 출금 API*

=== *4-1 성공*

operation::user-controller-test/withdraw-user-money-success[snippets='http-request,request-fields,http-response']

=== *4-2 실패 - 음수 유저 id*

operation::user-controller-test/withdraw-user-money-fail-user-id-negative[snippets='http-request,http-response']

=== *4-3 실패 - 존재하지 않는 유저 id*

operation::user-controller-test/withdraw-user-money-fail-user-id-not-exist[snippets='http-request,http-response']

=== *4-4 실패 - 음수의 출금액*

operation::user-controller-test/withdraw-user-money-fail-charge-negative[snippets='http-request,http-response']

=== *4-5 실패 - 소지 금액보다 큰 출금액*

operation::user-controller-test/withdraw-user-money-fail-charge-bigger-than-having[snippets='http-request,http-response']
