drop table if exists users cascade;
drop table if exists lotto cascade;
drop table if exists winning_lotto cascade;

create table if not exists users
(
    id        bigint generated by default as identity,
    money     integer      not null,
    user_name varchar(255) not null,
    user_role varchar(255) not null check (user_role in ('ROLE_USER', 'ROLE_ADMIN')),
    primary key (id)
);

ALTER TABLE users
    ADD CONSTRAINT UK_USERNAME_ON_USERS UNIQUE (user_name);

create table if not exists lotto
(
    id           bigint generated by default as identity,
    user_id      bigint,
    round        integer      not null,
    created_date timestamp(6) not null,
    numbers      varchar(255),
    primary key (id)
);

create index user_id_index on lotto (user_id);

ALTER TABLE lotto
    ADD CONSTRAINT FK_LOTTO_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

create table if not exists winning_lotto
(
    id       bigint generated by default as identity,
    lotto_id bigint  not null unique,
    round    integer not null,
    primary key (id)
);

create index lotto_id_index on winning_lotto (lotto_id);

ALTER TABLE winning_lotto
    ADD CONSTRAINT FK_WINNING_LOTTO_ON_LOTTO foreign key (lotto_id) references lotto (id);
