CREATE TABLE winning_lotto
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lotto_id BIGINT  NOT NULL UNIQUE,
    round    INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX lotto_id_index ON winning_lotto (lotto_id);

ALTER TABLE winning_lotto
    ADD CONSTRAINT FK_WINNING_LOTTO_ON_LOTTO FOREIGN KEY (lotto_id) REFERENCES lotto (id);
